# Generated by Django 4.1.7 on 2023-03-02 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('flag', models.URLField(blank=True, max_length=500)),
                ('color_scheme', models.CharField(blank=True, max_length=50)),
                ('hide_banners', models.BooleanField(default=False)),
                ('stasis', models.BooleanField(default=False)),
                ('stasis_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='register_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='registration ip address'),
        ),
    ]
