# Generated by Django 4.1.7 on 2023-03-03 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('funds', models.BigIntegerField(default=500000)),
                ('gdp_last_turn', models.PositiveBigIntegerField(default=0)),
                ('satisfaction', models.IntegerField(default=0)),
                ('se_relation', models.IntegerField(default=0)),
                ('nlr_relation', models.IntegerField(default=0)),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'Burrozil'), (2, 'Zebrica'), (3, 'Saddle Arabia'), (4, 'Przewalskia')])),
                ('subregion', models.PositiveSmallIntegerField(choices=[(1, 'North'), (2, 'Central'), (3, 'South')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
